--juste pour application Le mappage utilisateur/role sert à :

--Authentification : vérifier que l’utilisateur existe et que le mot de passe est correct.

--Autorisation : déterminer ce que l’utilisateur peut faire selon son rôle.

--Tests fonctionnels : tu peux simuler des actions pour chaque type d’utilisateur dans ton application ou tes triggers/procédures.


CREATE TABLE users_app (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) NOT NULL
);
INSERT INTO users_app (username, password, role)
VALUES ('pharmacien', 'pharmacien', 'PHARMACIEN');

INSERT INTO users_app (username, password, role)
VALUES ('vendeur', 'vendeur', 'VENDEUR');

INSERT INTO users_app (username, password, role)
VALUES ('comptable', 'comptable', 'COMPTABLE');

INSERT INTO users_app (username, password, role)
VALUES ('auditeur', 'auditeur', 'AUDITEUR');

-- Vérifier si la table existe
SELECT * FROM users_app;


-- Vider la table au cas où
DELETE FROM users_app;

-- Insérer les utilisateurs
INSERT INTO users_app (username, password, role) VALUES ('pharmacien', 'pharmacien', 'PHARMACIEN');
INSERT INTO users_app (username, password, role) VALUES ('vendeur', 'vendeur', 'VENDEUR');
INSERT INTO users_app (username, password, role) VALUES ('comptable', 'comptable', 'COMPTABLE');
INSERT INTO users_app (username, password, role) VALUES ('auditeur', 'auditeur', 'AUDITEUR');

-- IMPORTANT : Valider les changements !
COMMIT;

-- Vérifier
SELECT * FROM users_app;
SELECT COUNT(*) FROM users_app;